In [38]:
import pandas as pd

In [39]:
def calculate_missing_percentage(df):
    """ データフレームの各カラムの欠損率を計算する関数 
    Parameters: df (pd.DataFrame): 欠損率を計算する対象のデータフレーム 
    Returns: pd.Series: 各カラムの欠損率を含むシリーズ 
    """ 
    missing_percentage = df.isnull().mean() * 100 
    return missing_percentage

In [64]:
import pandas as pd
import numpy as np

def calculate_column_averages_with_nan(df):
    """
    データフレームの各列の平均値を計算し、数値型以外の列にはNaNを挿入する関数
    
    Parameters:
        df (pd.DataFrame): 平均値を計算する対象のデータフレーム
    
    Returns:
        pd.Series: 各列の平均値を含むシリーズ。ただし、数値型以外の列にはNaNを含む
    """
    averages = {}
    for column in df.columns:
        if pd.api.types.is_numeric_dtype(df[column]):
            averages[column] = df[column].mean()
        else:
            averages[column] = np.nan
    return pd.Series(averages)

In [58]:
df = pd.read_csv("train.csv")
df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_22044\2117274049.py:1: DtypeWarning: Columns (39,40,42,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("train.csv")

,target_ym,money_room,building_id,building_status,building_create_date,building_modify_date,building_type,building_name,building_name_ruby,homes_building_name,...,drugstore_distance,bank_distance,shopping_street_distance,est_other_name,est_other_distance,statuses,parking_keiyaku,money_hoshou_company,free_rent_duration,free_rent_gen_timing
0,202007,38000,a000002,1,2014-06-27 21:18:41,2024-05-25 00:45:07,3,Plaisirりんくう,NaN,プレジール りんくう,...,NaN,NaN,NaN,NaN,NaN,110702/210202/220101/220201/220301/230101/2308...,NaN,NaN,NaN,NaN
1,202107,103000,a000004,1,2017-02-05 20:43:26,2024-08-17 12:12:51,1,向原パークハイツ,NaN,向原パークハイツ,...,435.0,NaN,NaN,小竹向原駅,320.0,110301/210101/210201/210301/220101/220201/2203...,NaN,初回賃料等の50％、更新時1年毎に1万円,NaN,NaN
2,202101,50000,a000005,1,2014-06-27 20:32:50,2023-09-17 23:53:57,3,エナージ美香保,NaN,エナージ美香保,...,NaN,NaN,NaN,NaN,NaN,110201/110901/121001/210101/210202/220101/2202...,NaN,？月額家賃の50％、毎年10，000円 ？月額家賃の100％,NaN,NaN
3,202007,37000,a000008,1,2014-06-27 23:06:27,2024-03-08 00:10:05,3,エルディム希望,NaN,エルディム希望,...,NaN,NaN,NaN,生鮮食品オンリーワン 山手店,1114.0,121002/210202/210301/220101/220201/220301/2205...,NaN,契約時保証委託料：22，000円 月額保証委託料：賃料総額の2．2％又は5．5％,NaN,NaN
4,202101,33000,a000008,1,2014-06-27 23:06:27,2024-03-08 00:10:05,3,エルディム希望,NaN,エルディム希望,...,NaN,NaN,NaN,福山市立泉小学校,469.0,110301/121002/220201/220301/220501/230101/2302...,NaN,利用可（相談）,NaN,NaN

In [65]:
df

,target_ym,money_room,building_id,building_status,building_create_date,building_modify_date,building_type,building_name,building_name_ruby,homes_building_name,...,drugstore_distance,bank_distance,shopping_street_distance,est_other_name,est_other_distance,statuses,parking_keiyaku,money_hoshou_company,free_rent_duration,free_rent_gen_timing
0,202007,38000,a000002,1,2014-06-27 21:18:41,2024-05-25 00:45:07,3,Plaisirりんくう,NaN,プレジール りんくう,...,NaN,NaN,NaN,NaN,NaN,110702/210202/220101/220201/220301/230101/2308...,NaN,NaN,NaN,NaN
1,202107,103000,a000004,1,2017-02-05 20:43:26,2024-08-17 12:12:51,1,向原パークハイツ,NaN,向原パークハイツ,...,435.0,NaN,NaN,小竹向原駅,320.0,110301/210101/210201/210301/220101/220201/2203...,NaN,初回賃料等の50％、更新時1年毎に1万円,NaN,NaN
2,202101,50000,a000005,1,2014-06-27 20:32:50,2023-09-17 23:53:57,3,エナージ美香保,NaN,エナージ美香保,...,NaN,NaN,NaN,NaN,NaN,110201/110901/121001/210101/210202/220101/2202...,NaN,？月額家賃の50％、毎年10，000円 ？月額家賃の100％,NaN,NaN
3,202007,37000,a000008,1,2014-06-27 23:06:27,2024-03-08 00:10:05,3,エルディム希望,NaN,エルディム希望,...,NaN,NaN,NaN,生鮮食品オンリーワン 山手店,1114.0,121002/210202/210301/220101/220201/220301/2205...,NaN,契約時保証委託料：22，000円 月額保証委託料：賃料総額の2．2％又は5．5％,NaN,NaN
4,202101,33000,a000008,1,2014-06-27 23:06:27,2024-03-08 00:10:05,3,エルディム希望,NaN,エルディム希望,...,NaN,NaN,NaN,福山市立泉小学校,469.0,110301/121002/220201/220301/220501/230101/2302...,NaN,利用可（相談）,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584502,202001,64000,a545390,1,2016-02-21 05:33:37,2024-07-22 00:45:09,3,カーサディオランジュ,NaN,Casa di Orange,...,NaN,NaN,NaN,NaN,NaN,110301/110901/121002/210101/220101/220201/2203...,NaN,初回賃料総額の30％ 最低保証料15，000円 月額賃料総額の1．2％ 最低月額保証料600...,NaN,NaN
584503,202107,59000,a545392,1,2016-06-23 00:11:48,2021-11-13 00:10:05,3,ライトサファイヤ,NaN,ライトサファイア,...,522.0,NaN,NaN,NaN,NaN,110903/121001/210201/210301/220301/220501/2204...,NaN,初回保証料 22，000円、月額保証料 月額賃料等の2.2％又は5．5％,NaN,NaN
584504,202001,94000,a545393,1,2014-06-28 00:47:49,2024-08-15 02:09:08,1,AKテラス,NaN,AKテラス,...,100.0,480.0,NaN,NaN,NaN,110301/210101/210201/210301/220101/220201/2203...,NaN,ＪＩＤトリオ ３０％,NaN,NaN
584505,201907,42000,a545394,1,2014-06-27 23:41:43,2023-08-09 01:33:37,3,ハイツアプリコット,NaN,ハイツアプリコット,...,NaN,NaN,NaN,NaN,NaN,121001/210202/220301/220501/230801/290901/2901...,1.0,初回保証料月額賃料合計額の50％／月額保証料864円／更新保証料10．000円／年,NaN,NaN
584506,202101,42000,a545394,1,2014-06-27 23:41:43,2023-08-09 01:33:37,3,ハイツアプリコット,NaN,ハイツアプリコット,...,655.0,NaN,NaN,NaN,NaN,110301/110903/121001/210202/210301/220101/2203...,NaN,初回保証料50％（最低保証料なし）年間保証料(1年)10，000円 月額保証料1.3%,1.0,NaN

In [66]:
#missing_percentage
# missing_percentage = calculate_missing_percentage(df)
# missing_percentage.to_excel("train_data_missing_percentage.xlsx")

In [67]:
#cal_average
column_averages = calculate_column_averages_with_nan(df)
column_averages.to_excel("train_data_average_value.xlsx")

In [57]:
column_averages["genkyo_code"]

np.float64(1.8832209397616533)

In [42]:
deginition_df = pd.read_excel("date_deginition_edited_ver1.1.xlsx")
deginition_df.head()

,No.,本番データ特徴量名,特徴量の意味,補足,採否_original,採否,欠損補完方法,データ型,データ欠損率(%),MEMO,Unnamed: 10
0,1,target_ym,対象年月,各レコードの抽出対象年月日 yyyymm,△,×,0.0,int,0.0,NaN,NaN
1,2,money_room,賃料(代表),対応する物件の賃料。目的変数となる。,◎,◎,0.0,int,0.0,NaN,NaN
2,3,building_id,棟ID,AUTO_INCREMENT、UNSIGNED 確認事項参照,△,×,NaN,NaN,0.0,NaN,NaN
3,4,building_status,状態,1: 棟が存在する、9: 棟が存在しない,〇,〇,NaN,int,0.0,NaN,NaN
4,5,building_create_date,作成日時,データ作成日時,×,×,NaN,NaN,0.0,NaN,NaN

In [50]:
deginition_df.query('採否 == "〇"| 採否 == "△"')

,No.,本番データ特徴量名,特徴量の意味,補足,採否_original,採否,欠損補完方法,データ型,データ欠損率(%),MEMO,Unnamed: 10
3,4,building_status,状態,1: 棟が存在する、9: 棟が存在しない,〇,〇,NaN,int,0.000000,NaN,NaN
6,7,building_type,建物種別,"1: マンション, 3: アパート, その他: 欠損",〇,〇,NaN,int,0.000000,NaN,NaN
11,12,unit_count,総戸数/総区画数,物件の総数 (部屋:総戸数 土地:総区画数),〇,〇,1.0,int,33.352039,記載なしは1部屋と想定,NaN
15,16,building_structure,建物構造,1:木造 2:ブロック 3:鉄骨造 4:RC 5:SRC 6:PC 7:HPC 9:その他 ...,〇,〇,NaN,int,0.266549,カテゴリ変数は今回採用見送り,NaN
18,19,floor_count,建物階数(地上),NaN,〇,〇,0.0,int,0.009239,NaN,NaN
20,21,year_built,築年月,建築年月 yyyymm,〇,〇,199000.0,str,0.238492,NaN,NaN
48,49,room_floor,所在階数,NaN,〇,〇,NaN,NaN,0.365094,NaN,NaN
50,51,dwelling_unit_window_angle,主要採光面,NaN,〇,〇,NaN,NaN,8.634969,NaN,NaN
51,52,room_count,間取部屋数,NaN,〇,〇,NaN,NaN,1.188181,NaN,NaN
52,53,unit_area,専有面積,NaN,〇,〇,0.0,float,1.187668,NaN,NaN
74,75,bukken_type,物件種別,3101:賃貸マンション 3102:賃貸アパート,〇,〇,NaN,NaN,0.000000,NaN,NaN
78,79,post1,郵便番号(上位),7ケタ郵便番号の上位3桁,〇,〇,NaN,NaN,0.876807,NaN,NaN
79,80,post2,郵便番号(下位),7ケタ郵便番号の下位4桁,〇,〇,NaN,NaN,0.878689,NaN,NaN
80,81,addr1_1,都道府県,北海道、青森、秋田、東京等（JISコード） エリア情報参照,〇,〇,NaN,NaN,0.000000,NaN,NaN
81,82,addr1_2,市区郡町村,渋谷区、横浜市中区等（JISコード） エリア情報参照,〇,〇,NaN,NaN,0.000000,NaN,NaN
82,83,addr2_name,所在地 文字列,市区郡以降の文字列(常時入力) 郵便番号の順で取得して入力,〇,〇,NaN,NaN,0.005304,NaN,NaN
87,88,rosen_name1,路線名１,NaN,〇,〇,NaN,NaN,0.540627,NaN,NaN
88,89,eki_name1,駅名１,NaN,〇,〇,NaN,NaN,0.978260,NaN,NaN
91,92,walk_distance1,徒歩距離1,駅またはバス停からの距離（単位：m）。徒歩時間は距離÷80。,〇,〇,9999.0,int,0.540113,NaN,NaN
92,93,rosen_name2,路線名２,NaN,〇,〇,NaN,NaN,27.402751,NaN,NaN
93,94,eki_name2,駅名２,NaN,〇,〇,NaN,NaN,27.435086,NaN,NaN
96,97,walk_distance2,徒歩距離2,駅またはバス停からの距離（単位：m）。徒歩時間は距離÷80。,〇,〇,9999.0,int,27.402238,NaN,NaN
106,107,flg_new,新築・未入居フラグ,0:中古 1:新築・未入居,〇,〇,NaN,NaN,0.000000,NaN,NaN
108,109,room_kaisuu,部屋階数,部屋の所在階数 (マイナスの場合は地下),〇,〇,NaN,NaN,0.027545,NaN,NaN
109,110,snapshot_window_angle,向き,1:北 2:北東 3:東 4:南東 5:南 6:南西 7:西 8:北西 その他: 欠損,〇,〇,NaN,NaN,17.400818,NaN,NaN
110,111,madori_number_all,間取部屋数(代表),部屋の数,△,△,NaN,NaN,0.000000,NaN,NaN
111,112,madori_kind_all,間取部屋種類(代表),10:R 20:K 25:SK 30:DK 35:SDK 40:LK 45:SLK 50:L...,△,△,NaN,NaN,0.000000,NaN,NaN
125,126,parking_kubun,駐車場区分,1:空有 2:空無 3:近隣 4:無 (5:有 V3互換用) その他: 欠損,〇,〇,NaN,NaN,14.224979,NaN,NaN
129,130,genkyo_code,現況,(土地の場合)1:更地 2:古屋あり 10:古屋あり更地引渡可 (戸建・マン・外全・外一の場...,〇,〇,NaN,NaN,30.689624,NaN,NaN
138,139,convenience_distance,コンビニ距離,単位：m,〇,〇,NaN,NaN,30.557889,NaN,NaN
139,140,super_distance,スーパー距離,単位：m,〇,〇,NaN,NaN,30.311185,NaN,NaN
147,148,statuses,設備情報,スラッシュ(/) 区切り形式 物件マスタとは別コード 設備情報シート参照,〇,〇,NaN,NaN,0.000855,NaN,NaN

In [52]:
selected_col = deginition_df.query('採否 == "〇"| 採否 == "△"')["本番データ特徴量名"].values.tolist()
selected_col

['building_status',
 'building_type',
 'unit_count',
 'building_structure',
 'floor_count',
 'year_built',
 'room_floor',
 'dwelling_unit_window_angle',
 'room_count',
 'unit_area',
 'bukken_type',
 'post1',
 'post2',
 'addr1_1',
 'addr1_2',
 'addr2_name',
 'rosen_name1',
 'eki_name1',
 'walk_distance1',
 'rosen_name2',
 'eki_name2',
 'walk_distance2',
 'flg_new',
 'room_kaisuu',
 'snapshot_window_angle',
 'madori_number_all',
 'madori_kind_all',
 'parking_kubun',
 'genkyo_code',
 'convenience_distance',
 'super_distance',
 'statuses']

In [53]:
selected_data = df[selected_col].head(300)
selected_data.to_excel("train_selected.xlsx")

In [ ]:
sele